-- ETA-share + referral tables.
-- When User A taps "Share ETA" during nav, a row in eta_shares is created with
-- a short opaque token. The public portal page at /share/<token>.html polls
-- eta-share-fetch to render the live position and prompts non-installers to
-- install MonMap. If User B installs and signs up while a referral token is
-- present, both users get ₮500 via the wallet ledger.

-- ---------------------------------------------------------------------------
-- eta_shares: one share per trip (could be many over the trip's life if user
-- creates new ones, but enforced as one-active-per-trip via partial index).
-- ---------------------------------------------------------------------------
CREATE TABLE public.eta_shares (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  share_token   text        NOT NULL UNIQUE,                 -- 12-char base32, generated by edge fn
  user_id       uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  trip_id       uuid        NOT NULL REFERENCES public.nav_trips(id) ON DELETE CASCADE,
  expires_at    timestamptz NOT NULL,
  revoked_at    timestamptz,
  viewer_count  integer     NOT NULL DEFAULT 0,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX eta_shares_user_idx ON public.eta_shares (user_id, created_at DESC);
CREATE INDEX eta_shares_trip_idx ON public.eta_shares (trip_id);

CREATE UNIQUE INDEX eta_shares_one_active_per_trip
  ON public.eta_shares (trip_id)
  WHERE revoked_at IS NULL;

ALTER TABLE public.eta_shares ENABLE ROW LEVEL SECURITY;

CREATE POLICY "eta_shares_read_own"
  ON public.eta_shares FOR SELECT
  USING (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- eta_share_positions: latest known position per share. Written by the
-- nav-trip-heartbeat edge function when the trip has an active share.
-- Public read via the edge function eta-share-fetch only — no direct policy.
-- ---------------------------------------------------------------------------
CREATE TABLE public.eta_share_positions (
  share_id      uuid        PRIMARY KEY REFERENCES public.eta_shares(id) ON DELETE CASCADE,
  lat           numeric(10, 8) NOT NULL,
  lon           numeric(11, 8) NOT NULL,
  heading       real,
  eta_seconds   integer,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.eta_share_positions ENABLE ROW LEVEL SECURITY;
-- No client policy — edge function uses service role to read/write.

CREATE TRIGGER eta_share_positions_set_updated_at
  BEFORE UPDATE ON public.eta_share_positions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- referrals: one bonus per invitee. Inviter is the user that owned the
-- share_token; invitee is the freshly signed-up user.
-- ---------------------------------------------------------------------------
CREATE TABLE public.referrals (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  inviter_user_id   uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  invitee_user_id   uuid        NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  share_token       text        NOT NULL,
  status            text        NOT NULL DEFAULT 'awarded' CHECK (status IN ('pending','awarded','rejected')),
  reject_reason     text,
  awarded_at        timestamptz NOT NULL DEFAULT now(),
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX referrals_inviter_idx ON public.referrals (inviter_user_id, awarded_at DESC);

ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "referrals_read_as_inviter_or_invitee"
  ON public.referrals FOR SELECT
  USING (auth.uid() = inviter_user_id OR auth.uid() = invitee_user_id);

-- ---------------------------------------------------------------------------
-- Constants.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.referral_bonus_mnt()
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 500 $$;

CREATE OR REPLACE FUNCTION public.referral_inviter_window_days()
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 30 $$;

CREATE OR REPLACE FUNCTION public.referral_inviter_window_cap()
RETURNS integer LANGUAGE sql IMMUTABLE AS $$ SELECT 50 $$;

-- ---------------------------------------------------------------------------
-- RPC: redeem_referral
-- Called from the referral-claim edge function (service role) once the
-- invitee has authenticated. Validates the share token, anti-abuse checks,
-- and credits both users atomically. Returns the new referral_id, or NULL
-- if rejected.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.redeem_referral(
  p_share_token   text,
  p_invitee_id    uuid
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_inviter           uuid;
  v_invitee_created   timestamptz;
  v_invitee_bookings  integer;
  v_inviter_recent    integer;
  v_ref_id            uuid;
  v_bonus             integer := public.referral_bonus_mnt();
  v_window_days       integer := public.referral_inviter_window_days();
  v_window_cap        integer := public.referral_inviter_window_cap();
BEGIN
  IF p_share_token IS NULL OR length(p_share_token) < 8 THEN
    RAISE EXCEPTION 'invalid_token' USING ERRCODE = 'P0001';
  END IF;

  -- Lookup inviter by token. Token is unique on eta_shares, so this is exact.
  SELECT user_id INTO v_inviter
  FROM public.eta_shares
  WHERE share_token = p_share_token;

  IF v_inviter IS NULL THEN
    RAISE EXCEPTION 'unknown_token' USING ERRCODE = 'P0002';
  END IF;

  -- No self-referral.
  IF v_inviter = p_invitee_id THEN
    INSERT INTO public.referrals (inviter_user_id, invitee_user_id, share_token, status, reject_reason)
    VALUES (v_inviter, p_invitee_id, p_share_token, 'rejected', 'self_referral')
    ON CONFLICT (invitee_user_id) DO NOTHING;
    RETURN NULL;
  END IF;

  -- Invitee must be a brand-new account (created <24h ago) with no prior bookings.
  SELECT created_at INTO v_invitee_created FROM auth.users WHERE id = p_invitee_id;
  IF v_invitee_created IS NULL OR v_invitee_created < now() - interval '24 hours' THEN
    INSERT INTO public.referrals (inviter_user_id, invitee_user_id, share_token, status, reject_reason)
    VALUES (v_inviter, p_invitee_id, p_share_token, 'rejected', 'invitee_not_new')
    ON CONFLICT (invitee_user_id) DO NOTHING;
    RETURN NULL;
  END IF;

  SELECT COUNT(*) INTO v_invitee_bookings
  FROM public.bookings WHERE user_id = p_invitee_id;
  IF v_invitee_bookings > 0 THEN
    INSERT INTO public.referrals (inviter_user_id, invitee_user_id, share_token, status, reject_reason)
    VALUES (v_inviter, p_invitee_id, p_share_token, 'rejected', 'invitee_has_history')
    ON CONFLICT (invitee_user_id) DO NOTHING;
    RETURN NULL;
  END IF;

  -- Inviter rate limit: max 50 awarded referrals in 30 days.
  SELECT COUNT(*) INTO v_inviter_recent
  FROM public.referrals
  WHERE inviter_user_id = v_inviter
    AND status = 'awarded'
    AND awarded_at > now() - (v_window_days || ' days')::interval;
  IF v_inviter_recent >= v_window_cap THEN
    INSERT INTO public.referrals (inviter_user_id, invitee_user_id, share_token, status, reject_reason)
    VALUES (v_inviter, p_invitee_id, p_share_token, 'rejected', 'inviter_cap')
    ON CONFLICT (invitee_user_id) DO NOTHING;
    RETURN NULL;
  END IF;

  -- All checks passed — insert award. UNIQUE on invitee_user_id protects
  -- against double-claim.
  INSERT INTO public.referrals (inviter_user_id, invitee_user_id, share_token, status)
  VALUES (v_inviter, p_invitee_id, p_share_token, 'awarded')
  RETURNING id INTO v_ref_id;

  PERFORM public.credit_wallet(v_inviter,    v_bonus, 'referral_bonus', v_ref_id, jsonb_build_object('role','inviter'));
  PERFORM public.credit_wallet(p_invitee_id, v_bonus, 'referral_bonus', v_ref_id, jsonb_build_object('role','invitee'));

  RETURN v_ref_id;
END;
$$;

REVOKE ALL ON FUNCTION public.redeem_referral(text, uuid) FROM PUBLIC;
